PropertyManagement.Web/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PropertyManagement.BusinessObjectLayer;
using PropertyManagement.BusinessObjectLayer.ViewModels;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace PropertyManagement.Web.Controllers
{
    public class PropertyController : Controller
    {
        private readonly IPropertyService _propertyService;
        private readonly IStatusService _statusService;
        private readonly IRepairService _repairService;
        private readonly ICommonListService _commonListService;


        public PropertyController(IPropertyService propertyService, IStatusService statusService, IRepairService repairService, ICommonListService commonListService)
        {
            _propertyService = propertyService;
            _statusService = statusService;
            _repairService = repairService;
            _commonListService = commonListService;
        }

        public IActionResult TabView(string PropertyId, string TabId)
        {
            string tabName = "";
            ViewBag.PropertyId = PropertyId;
            ViewBag.TabId = TabId;

            if (TabId == "1")
                tabName = "Edit";
            else 
                tabName = "RepairList";
            ViewBag.TabName = tabName;
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var query = await _propertyService.PropertyList();
            return View(query);
        }

        [HttpGet]
        public ActionResult Create()
        {
            PropertyTypeDropDownList("PropertyTypeId", "PropertyTypeName", 0);
            StatesDropDownList("StateId", "StateName", 0);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(int PropertyTypeId, string Address, string UnitNumber, string City, int StateId, string ZipCode, string PurchasePrice, string PurchaseDate, string SoldPrice, string SoldDate, string Notes)
        {
            try
            {
                int StatusId = 0;
                int PropertyId = 0;
                await this._propertyService.SavePropertyData(PropertyId, PropertyTypeId, Address, UnitNumber, City, StateId, ZipCode, PurchasePrice, PurchaseDate, SoldPrice, SoldDate, Notes, StatusId);
                return RedirectToAction("Index");
            }
            catch (SqlException ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int PropertyId)
        {
            int StatusTypeId = 0;
            var editProperty = await this._propertyService.PropertyById(PropertyId);
            PropertyTypeDropDownList("PropertyTypeId", "PropertyTypeName", editProperty.PropertyTypeId);
            StatusDropDownList("StatusId", "StatusName", editProperty.StatusId, StatusTypeId);
            StatesDropDownList("StateId", "StateName", editProperty.StateId);
            ViewBag.PropertyAddress = editProperty.FullAddress;
            ViewBag.PropertyId = PropertyId;

            return PartialView(editProperty);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int PropertyId, int PropertyTypeId, string Address, string UnitNumber, string City, int StateId, string ZipCode, string PurchasePrice, string PurchaseDate, string SoldPrice, string SoldDate, string Notes, int StatusId)
        {
            try
            {
                await this._propertyService.SavePropertyData(PropertyId, PropertyTypeId, Address, UnitNumber, City, StateId, ZipCode, PurchasePrice, PurchaseDate, SoldPrice, SoldDate, Notes, StatusId);
                return RedirectToAction("Index");
            }
            catch (SqlException ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            PropertyTypeDropDownList("PropertyTypeId", "PropertyTypeName", PropertyTypeId);
            StatusDropDownList("StatusId", "StatusName", StatusId, 0);
            StatesDropDownList("StateId", "StateName", StateId);
            return View();
        }

        //Status
        public void StatusDropDownList(string statusId, string statusName, int ItemId, int StatusTypeId)
        {
             List<StatusViewModel> status = this._statusService.StatusList(StatusTypeId);

           var selectList = new SelectList(status, statusId, statusName, ItemId);
            ViewBag.Status = selectList;
        }

        //States
        public void StatesDropDownList(string StateId, string StateCode, int ItemId)
        {

            List<StatesViewModel> states = this._commonListService.StatesList();

            var selectList = new SelectList(states, StateId, StateCode, ItemId);
            ViewBag.States = selectList;
        }

        //Property Type
        public void PropertyTypeDropDownList(string PropertyTypeId, string PropertyTypeName, int ItemId)
        {

            List<PropertyTypeViewModel> propertytypes = this._commonListService.PropertyTypeList();

            var selectList = new SelectList(propertytypes, PropertyTypeId, PropertyTypeName, ItemId);
            ViewBag.PropertyTypes = selectList;
        }

        /***************************************************************** REPAIR SECTION ************************************************/

        public async Task<IActionResult> RepairList(int PropertyId)
        {
            @ViewBag.PropertyId = PropertyId;
            var property = await this._propertyService.PropertyById(PropertyId);
            ViewBag.PropertyInformation = property.FullAddress;

            var query = await _repairService.RepairList(PropertyId);
  
            return PartialView(query);
        }



        [HttpGet]
        public async Task<IActionResult> AddEditRepair(int RepairId = 0, int PropertyId = 0)
        {
            try
            {
                var property = await this._propertyService.PropertyById(PropertyId);
                ViewBag.PropertyInformation = property.Address + " - " + property.City;
                

                if (RepairId > 0)
                {
                    int StatusTypeId = 2;
                    var query = await this._repairService.RepairById(RepairId);
                    UrgencyTypeDropDownList("UrgencyId", "UrgencyName", query.UrgencyId);
                    ServiceCategoryTypeDropDownList("ServiceCategoryId", "ServiceCategoryName", query.ServiceCategoryId);
                    ProfessionalServiceTypeDropDownList("ProfessionalServiceId", "CompanyName", query.ProfessionalServiceId);
                    RequestTypeDropDownList("RequestTypeId", "RequestTypeName", query.RequestTypeId);
                    PaymentMethodTypeDropDownList("PaymentMethodId", "PaymentMethodName", query.PaymentTypeId);
                    StatusDropDownList("StatusId", "StatusName", query.StatusId, StatusTypeId);
                    ViewBag.TableTitle = "Edit Repair Information";
                    return PartialView(query);
                }
                else
                {
                    UrgencyTypeDropDownList("UrgencyId", "UrgencyName", 0);
                    ServiceCategoryTypeDropDownList("ServiceCategoryId", "ServiceCategoryName", 0);
                    ProfessionalServiceTypeDropDownList("ProfessionalServiceId", "CompanyName", 0);
                    RequestTypeDropDownList("RequestTypeId", "RequestTypeName", 0);
                    PaymentMethodTypeDropDownList("PaymentMethodId", "PaymentMethodName", 0);

                    ViewBag.TableTitle = "Add Repair Information";

                    RepairViewModel rVM = new RepairViewModel();
                    rVM.RepairId = RepairId;
                    rVM.PropertyId = PropertyId;
                    return PartialView(rVM);
                }
                    
            }
            catch (SqlException ex)
            {
                var errorMessage = ex.Message;
                return Content(errorMessage.ToString(), "text/plain");
            }

        }

        [HttpPost]
        public async Task<IActionResult> SaveRepairData(int RepairId, int PropertyId, int UrgencyId, int RequestTypeId, int ServiceCategoryId, int ProfessionalServiceId, string Description,
                                                       string RepairReportedDate, string RepairCompletedDate, string TechnicianName, string RepairCost, int PaymentTypeId, string Notes, int StatusId)
        {
            try
            {
                await this._repairService.SaveRepairData(RepairId, PropertyId, UrgencyId, RequestTypeId, ServiceCategoryId, ProfessionalServiceId, Description,
                                                       RepairReportedDate, RepairCompletedDate, TechnicianName, RepairCost, PaymentTypeId, Notes, StatusId);
                //return RedirectToAction("TabView?PropertyId=" + PropertyId, 2);
            }
            catch (SqlException ex)
            {
                var errorMessage = ex.Message;
                return Content(errorMessage.ToString(), "text/plain");
            }
            return Content("");
        }
        //urgency
        public void UrgencyTypeDropDownList(string UrgencyId, string UrgencyName, int ItemId)
        {

            List<UrgencyTypeViewModel> urgency = this._commonListService.UrgencyList();

            var selectList = new SelectList(urgency, UrgencyId, UrgencyName, ItemId);
            ViewBag.UrgencyTypes = selectList;
        }
        //service category
        public void ServiceCategoryTypeDropDownList(string ServiceCategoryId, string ServiceCategoryName, int ItemId)
        {

            List<ServiceCategoryTypeViewModel> service = this._commonListService.ServiceCategoryList();

            var selectList = new SelectList(service, ServiceCategoryId, ServiceCategoryName, ItemId);

PropertyManagement.Web/Views/Property/AddEditRepair.cshtml
@model PropertyManagement.BusinessObjectLayer.ViewModels.RepairViewModel
<div class="row">
    <div class="col-xl-12">
        <div class="card mb-12">
            <form asp-action="AddEditRepair" method="post" asp-controller="Property" class="form-horizontal" id="repairForm">
             
                <div id="tasks-inner">
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="RepairId" id="RepairId" />
                        <input type="hidden" asp-for="PropertyId" id="PropertyId" />
                        <div class="form-group required row">
                            <label asp-for="RequestTypeId" class="col-md-2 col-form-label">Request Type:</label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(model => model.RequestTypeId, new SelectList(ViewBag.RequestTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddRequestType", @class = "form-control" })
                                <span asp-validation-for="RequestTypeId" class="text-danger"></span>
                            </div>
                            <label asp-for="UrgencyId" class="col-md-2 col-form-label">Urgency:</label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(model => model.UrgencyId, new SelectList(ViewBag.UrgencyTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddUrgency", @class = "form-control" })
                                <span asp-validation-for="UrgencyId" class="text-danger"></span>
                            </div>
                            <label asp-for="ServiceCategoryId" class="col-md-2 col-form-label">Service Type:</label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(model => model.ServiceCategoryId, new SelectList(ViewBag.ServiceCategoryTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddServiceCategory", @class = "form-control" })
                                <span asp-validation-for="ServiceCategoryId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group required row">
                            <label asp-for="Description" class="col-md-2 col-form-label">Description:</label>
                            <div class="col-md-10">
                                <textarea class="form-control" rows="3" id="txtDescription" asp-for="Description"></textarea>
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label asp-for="RepairReportedDate" class="col-md-2 col-form-label">Date Reported:</label>
                            <div class="col-md-4">
                                <input asp-for="RepairReportedDate" id="txtRepairReportedDate" class="form-control" required placeholder="MM/DD/YYYY" />
                                <span asp-validation-for="RepairReportedDate" class="text-danger"></span>
                            </div>

                            <label asp-for="RepairCompletedDate" class="col-md-2 col-form-label-nrq">Date Completed:</label>
                            <div class="col-md-4">
                                <input asp-for="RepairCompletedDate" id="txtRepairCompletedDate" class="form-control" placeholder="MM/DD/YYYY" />
                                <span asp-validation-for="RepairCompletedDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label asp-for="ProfessionalServiceId" class="col-md-2 col-form-label">Company Name:</label>
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.ProfessionalServiceId, new SelectList(ViewBag.ProfessionalServiceTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddProfessionalService", @class = "form-control" })
                                <span asp-validation-for="ProfessionalServiceId" class="text-danger"></span>
                            </div>

                            <label asp-for="TechnicianName" class="col-md-2 col-form-label-nrq">Technician Name:</label>
                            <div class="col-md-4">
                                <input asp-for="TechnicianName" id="txtTechnicianName" class="form-control" />
                                <span asp-validation-for="TechnicianName" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group required row">
                            <label asp-for="RepairCost" class="col-md-2 col-form-label-nrq">Repair Cost:</label>
                            <div class="col-md-4">
                                <input asp-for="RepairCost" id="txtRepairCost" class="form-control" required />
                                <span asp-validation-for="RepairCost" class="text-danger"></span>
                            </div>

                            <label asp-for="PaymentTypeId" class="col-md-2 col-form-label">Payment Type:</label>
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.PaymentTypeId, new SelectList(ViewBag.PaymentMethodTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddPaymentType", @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group required row">
                            @if (Model.RepairId > 0)
                            {
                                <label asp-for="StatusId" class="col-md-2 col-form-label">Status:</label>
                                <div class="col-md-4">
                                    @Html.DropDownListFor(model => model.StatusId, new SelectList(ViewBag.Status as System.Collections.IEnumerable, "Value", "Text"), new { id = "ddStatus", @class = "form-control" })
                                    <span asp-validation-for="StatusId" class="text-danger"></span>
                                </div>
                            }
                        </div>
                        <div class="form-group row">
                            <label asp-for="Notes" class="col-md-2 col-form-label">Notes:</label>
                            <div class="col-md-10">
                                <textarea class="form-control" rows="3" id="txtNotes" asp-for="Notes"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <span style="color:red;" id="spCreateMessage">@ViewBag.ErrorMessage</span>
                            </div>
                        </div>
                    </div>
                    <hr class="m-0">
                </div>
                @*<div class="card-footer" style="text-align:right;">
                    <div class="pull-right">
                        <a href="/Property/RepairList?PropertyId=@Model.PropertyId" class="btn btn-secondary">Back to List</a>
                        <button type="submit" class="lnkAdd btn btn-primary" id="btnSave">Save</button>
                    </div>
                </div>*@
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $(function () {
        $("#txtRepairReportedDate").datepicker();
        $("#txtRepairCompletedDate").datepicker();

        $(".lnkAdd").click(function () {
            var repairId = $('#RepairId').val();
            var propertyId = $("#PropertyId").val();
            var ddRequestType = $("#ddRequestType").val();
            var ddUrgency = $("#ddUrgency").val();
            var ddServiceCategory = $("#ddServiceCategory").val();
            var ddProfessionalService = $("#ddProfessionalService").val();
            var description = $("#txtDescription").val();
            var repairReportedDate = $("#txtRepairReportedDate").val();
            var repairCompletedDate = $("#txtRepairCompletedDate").val();
            var technicianName = $("#txtTechnicianName").val();
            var repairCost = $("#txtRepairCost").val();
            var ddPaymentType = $("#ddPaymentType").val();
            var ddStatus = $("#ddStatus").val();
            var notes = $("#txtNotes").val();

            if (ddRequestType == "") {
                $.alert("Select request type.", "Warning");
                $("#ddRequestType").addClass('errorClass');
                return false;
            }
            if (ddUrgency == "") {
                $.alert("Select urgency type.", "Warning");
                $("#ddUrgency").addClass('errorClass');
                return false;
            }
            if (ddServiceCategory == "") {
                $.alert("Select service type.", "Warning");
                $("#ddServiceCategory").addClass('errorClass');
                return false;
            }
            if (description == "") {
                $.alert("Enter description of the issue reported.", "Warning");
                $("#txtDescription").addClass('errorClass');
                return false;
            }
            if (repairReportedDate == "") {
                $.alert("Enter date when issue was reported.", "Warning");
                $("#txtRepairReportedDate").addClass('errorClass');
                return false;
            }
            if (ddProfessionalService == "") {
                $.alert("Select company name.", "Warning");
                $("#ddProfessionalService").addClass('errorClass');
                return false;
            }



        });
    });
</script>

PropertyManagement.Web/Views/Property/Create.cshtml
@model PropertyManagement.BusinessObjectLayer.ViewModels.PropertyViewModel
<div class="row">
    <div class="col-xl-1">
    </div>
    <div class="col-xl-9">
        <div class="card mb-9">
            <form asp-action="Create" method="post" asp-controller="Property" class="form-horizontal" id="propertyForm">
                <h6 class="card-header with-elements">Add New Property</h6>
                <div id="tasks-inner">
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="@Model.PropertyId" id="PropertyId" value="0" class="form-control" />
                        <div class="form-group required row">
                            <label asp-for="Address" class="col-form-label col-sm-1 text-sm-right">Address:</label>
                            <div class="col-md-7">
                                <input asp-for="Address" class="form-control" required id="txtAddress" />
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <label asp-for="UnitNumber" class="col-form-label-nrq col-sm-1 text-sm-right">Unit #:</label>
                            <div class="col-md-3">
                                <input asp-for="UnitNumber" class="form-control" id="txtUnitNumber" />
                                <span asp-validation-for="UnitNumber" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label asp-for="City" class="col-form-label col-sm-1 text-sm-right">City:</label>
                            <div class="col-md-3">
                                <input asp-for="City" class="form-control" required id="txtCity" />
                                <span asp-validation-for="City" class="text-danger"></span>
                            </div>
                            <label asp-for="StateId" class="col-form-label col-sm-1 text-sm-right">State:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(model => model.StateId, new SelectList(ViewBag.States as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddStates", @class = "form-control" })
                                <span asp-validation-for="StateId" class="text-danger"></span>
                            </div>
                            <label asp-for="ZipCode" class="col-form-label col-sm-1 text-sm-right">Zip Code:</label>
                            <div class="col-md-3">
                                <input asp-for="ZipCode" class="form-control" required id="txtZipCode" />
                                <span asp-validation-for="ZipCode" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label asp-for="PurchaseDate" class="col-form-label col-sm-1 text-sm-right">Purchase Date:</label>
                            <div class="col-md-3">
                                <input asp-for="PurchaseDate" class="form-control" placeholder="MM/DD/YYYY" id="txtPurchaseDate" />
                                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
                            </div>

                            <label asp-for="SoldDate" class="col-form-label-nrq col-sm-1 text-sm-right">Sold Date:</label>
                            <div class="col-md-3">
                                <input asp-for="SoldDate" class="form-control" placeholder="MM/DD/YYYY" id="txtSoldDate" />
                                <span asp-validation-for="SoldDate" class="text-danger"></span>
                            </div>
                            <label asp-for="PropertyTypeId" class="col-form-label col-sm-1 text-sm-right">Class:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(model => model.PropertyTypeId, new SelectList(ViewBag.PropertyTypes as System.Collections.IEnumerable, "Value", "Text"), "", new { id = "ddPropertyType", @class = "form-control" })
                                <span asp-validation-for="PropertyTypeId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label asp-for="PurchasePrice" class="col-form-label col-sm-1 text-sm-right">Purchase Price:</label>
                            <div class="col-md-3">
                                <input asp-for="PurchasePrice" class="form-control" id="txtPurchasePrice"/>
                                <span asp-validation-for="PurchasePrice" class="text-danger"></span>
                            </div>

                            <label asp-for="SoldPrice" class="col-form-label-nrq col-sm-1 text-sm-right">Sold Price:</label>
                            <div class="col-md-3">
                                <input asp-for="SoldPrice" class="form-control" id="txtSoldDate"/>
                                <span asp-validation-for="SoldPrice" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label asp-for="Notes" class="col-md-1 col-form-label">Notes:</label>
                            <div class="col-md-11">
                                <textarea class="form-control" rows="3" id="txtNotes" asp-for="Notes"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <span style="color:red;" id="spMessage">@ViewBag.ErrorMessage</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer" style="text-align:right;">
                    <div class="pull-right">
                        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                        <button type="submit" class="lnkAdd btn btn-primary" id="btnSave">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-xl-1">
    </div>
</div>

<script>
    $(function () {
        $("#PurchaseDate").datepicker();
        $("#SoldDate").datepicker();

        $(".lnkAdd").click(function () {
            var sAddress = $("#txtAddress").val();
            var sCity = $("#txtCity").val();
            var sState = $("#ddStates").val();
            var sZipCode = $("#txtPurchaseDate").val();
            var sPurchasePrice = $("#txtPurchasePrice").val();
            var sPurchaseDate = $("#txtPurchaseDate").val();
            var sClass = $("#ddPropertyType").val();

            if (sAddress == "") {
                $.alert("Address is required field.", "WARNING");
                $("#txtAddress").addClass('errorClass');
                return false;
            }
            if (sCity == "") {
                $.alert("City is required field.", "WARNING");
                $("#txtCity").addClass('errorClass');
                return false;
            }
            if (sState == "") {
                $.alert("State is required field.", "WARNING");
                $("#ddState").addClass('errorClass');
                return false;
            }
            if (sZipCode == "") {
                $.alert("ZipCode is required field.", "WARNING");
                $("#txtZipCode").addClass('errorClass');
                return false;
            }
            if (sPurchasePrice == "") {
                $.alert("PurchasePrice is required field.", "WARNING");
                $("#txtPurchasePrice").addClass('errorClass');
                return false;
            }
            if (sPurchaseDate == "") {
                $.alert("PurchaseDate is required field.", "WARNING");
                $("#txtPurchaseDate").addClass('errorClass');
                return false;
            }
            if (sClass == "") {
                $.alert("Property class is required field.", "WARNING");
                $("#ddPropertyType").addClass('errorClass');
                return false;
            }

        });
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyManagement.Web/Views/Property/TabView.cshtml
<div class="box box-info " id="nopcommerce-news-box">
    <div class="box-body">
        <div class="row">
            <div id="tabs" class="col-xl-12">
            <div class="nav-tabs-top mb-4">
                <ul  class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" id="1" href="#edit">Edit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" id="2" href="#repair">Repairs</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="edit">
                        <div class="card-body">
                            <div id="ProductsDiv1">
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="repair">
                        <div class="card-body">
                            <div id="ProductsDiv2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

<input type="hidden" id="txtPropertyId" value="@ViewBag.PropertyId" />
<script type="text/javascript">
            $(function () {
                var propertyId = $("#txtPropertyId").val();
                var tabId = '@ViewBag.TabId';

                loadPartialView(tabId, propertyId);

                $(".nav-link").click(function () {
                    var _propertyId = $("#txtPropertyId").val();
                    var _tabId = $(this).attr("id");

                    loadPartialView(_tabId, _propertyId);

                });

            });
            function loadPartialView(tabId, id) {
                var _tabName = "";
                if (tabId == 1) {
                    _tabName = "Edit";

                    $("#2").removeClass("active");
                    $("#1").addClass("active");
                    $("#repair").removeClass("show active");
                    $("#edit").addClass("show active");
                }
                if (tabId == 2) {
                    _tabName = "RepairList";

                    $("#1").removeClass("active");
                    $("#2").addClass("active");
                    $("#edit").removeClass("show active");
                    $("#repair").addClass("show active");
                }
                $.ajax({
                    url: "/Property/" + _tabName,
                    type: 'get',
                    dataType: "html",
                    data: { PropertyId: id },
                    success: function (data) {
                        $('#ProductsDiv' + tabId).html(data); //populate the tab content.
                    },
                    error: function () {
                        alert("error");
                    }
                });

            }


        </script>