PropertyManagement.Web/Controllers/LeaseController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PropertyManagement.BusinessObjectLayer;
using PropertyManagement.BusinessObjectLayer.ViewModels;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PropertyManagement.Web.Controllers
{
    public class LeaseController : Controller
    {
        private readonly ILeaseService _leaseService;
        private readonly IPropertyService _propertyService;
        private readonly IStatusService _statusService;
        private readonly ICommonListService _commonListService;
        private readonly ITenantService _tenantService;

        
        

        public LeaseController(ILeaseService leaseService, IPropertyService propertyService, IStatusService statusService, IRepairService repairService, ICommonListService commonListService, ITenantService tenantService)
        {
            _leaseService = leaseService;
            _propertyService = propertyService;
            _statusService = statusService;
            _commonListService = commonListService;
            _tenantService = tenantService;
        }

        public async Task<IActionResult> Index(int Year = 0, int Month = 0)
        {

            if (Year == 0)
            {
                int _year = DateTime.Now.Year;
                Year = _year;
            }
            if (Month == 0)
            {
                int _month = DateTime.Now.Month;
                Month = _month;
            }

            var years =  _commonListService.YearList();
            var selectedYear = DateTime.Now.Year;
            SelectList ListYears = new SelectList(years, "Year", "Year", selectedYear);         
            ViewBag.Years = ListYears;
            ViewBag.Months =  _commonListService.MonthList();
            ViewBag.SelectedMonth = Month;
            ViewBag.SelectedYear = Year;

            var query = await _leaseService.LeaseList(Year, Month);
            return View(query);
        }

        public async Task<IActionResult> AddProperties()
        {
            var years = _commonListService.YearList();
            var selectedYear = DateTime.Now.Year;
            SelectList ListYears = new SelectList(years, "Year", "Year", selectedYear);
            ViewBag.Years = ListYears;
            var query = await _leaseService.PropertiesForLease();
            return PartialView(query);
        }

        [HttpPost]
        public async Task<IActionResult> SaveSelectedProperties(int Year, string PropertyIds)
        {
            try
            {
                PropertyIds = PropertyIds.Remove(PropertyIds.Length - 1, 1);

                await this._leaseService.SaveSelectedProperties(Year, PropertyIds);
            }
            catch (SqlException ex)
            {
                var errorMessage = ex.Message;
                return Content(errorMessage.ToString(), "text/plain");
            }
            return Content("");
        }
        [HttpGet]
        public async Task<IActionResult> EditLease(int LeaseId)
        {
            var Lease = await this._leaseService.LeaseById(LeaseId);
            TenantsDropDownList("TenantId", "FullName", Lease.TenantId);

            return PartialView(Lease);
        }

        public void TenantsDropDownList(string TenantId, string FullName, int TenantIdSel)
        {
            List<TenantActiveListViewModel> tenants = this._tenantService.TenantActive();

            var selectList = new SelectList(tenants, TenantId, FullName, TenantIdSel);
            ViewBag.Tenants = selectList;
        }

        [HttpPost]
        public async Task<IActionResult> SaveDataLease(int LeaseId, int TenantId, decimal RentAmount, decimal AmountRecieved, string DateReceived, decimal PastDue, decimal CurrentDue, decimal BalanceDue, string Notes)
        {
            try
            {
                await this._leaseService.LeaseUpdate(LeaseId, TenantId, RentAmount, AmountRecieved, DateReceived, PastDue, CurrentDue, BalanceDue, Notes);
            }
            catch (SqlException ex)
            {
                var errorMessage = ex.Message;
                return Content(errorMessage.ToString(), "text/plain");
            }
            return Content("");
        }
    }
}

PropertyManagement.Web/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PropertyManagement.BusinessObjectLayer;
using System.Data.SqlClient;

namespace PropertyManagement.Web.Controllers
{
    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;

        public StatusController(IStatusService statusService)
        {
            _statusService = statusService;
        }
        public async Task<IActionResult> Index()
        {
            var query = await _statusService.StatusList();
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int StatusId = 0)
        {
            if (StatusId > 0)
            {
                var query = await this._statusService.StatusById(StatusId);
                ViewBag.StatusTitle = "Edit Status";
                return View(query);
            }
            else
            {
                ViewBag.StatusTitle = "Add Status";
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(int StatusId, string StatusName, int StatusType )
        {
            try
            {
                    await this._statusService.SaveStatusData(StatusName, StatusId, StatusType);
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }
            return View();
        }

    }
}

PropertyManagement.Web/Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PropertyManagement.BusinessObjectLayer;
using PropertyManagement.BusinessObjectLayer.ViewModels;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;


namespace PropertyManagement.Web.Controllers
{
    public class TenantController : Controller
    {
        private readonly ITenantService _tenantService;
        private readonly IPropertyService _propertyService;
        private readonly IStatusService _statusService;
        private readonly ICommonListService _commonListService;

        public TenantController(ITenantService tenantService, IPropertyService propertyService, IStatusService statusService, ICommonListService commonListService)
        {
            _tenantService = tenantService;
            _propertyService = propertyService;
            _statusService = statusService;
            _commonListService = commonListService;
        }

        public IActionResult TabView(string id)
        {
            ViewBag.TenantId = id;
            return View();
        }
        public async Task<IActionResult> Index()
        {
            var query = await _tenantService.TenantList();
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> CreateEditTenant(int TenantId = 0)
        {           
            if (TenantId > 0)
            {
                var query = await this._tenantService.TenantById(TenantId);
                StatusDropDownList("StatusId", "StatusName", query.StatusId);
                PropertyDropDownListForLease("PropertyId", "FullAddress", query.PropertyId);
                return View(query);
            }
            else
            {
                TenantViewModel tVM = new TenantViewModel();
                tVM.TenantId = 0;
                PropertyDropDownListForLease("PropertyId", "FullAddress", 0);
                return View(tVM);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateEditTenant(int TenantId, string FirstName, string LastName, string DOB, int Age, string Gender, string DriverLicenseNo, string Phone, string Email, 
                                              string EmergencyContact, int PropertyId, string MoveInDate, string MoveOutDate, decimal MonthlyRent, decimal DepositAmount, 
                                              decimal DepositReturned, decimal DepositWithHold, string Notes, decimal ProratedRent, int StatusId)
        {
            try
            {
                await this._tenantService.SaveTenantData(TenantId, FirstName, LastName, DOB, Age, Gender, DriverLicenseNo, Phone, Email,
                                              EmergencyContact, PropertyId, MoveInDate, MoveOutDate, MonthlyRent, DepositAmount,
                                              DepositReturned, DepositWithHold, Notes, ProratedRent, StatusId);
                return RedirectToAction("Index");
            }
            catch (SqlException ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return View();
        }

        public void StatusDropDownList(string statusId, string statusName, int ItemId)
        {
            int StatusTypeId = 1;

            List<StatusViewModel> status = this._statusService.StatusList(StatusTypeId);

            var selectList = new SelectList(status, statusId, statusName, ItemId);
            ViewBag.Status = selectList;
        }
        
        public void PropertyDropDownList(string propertyId, string Address, int ItemId, int PropertyStatusId)
        {

            List <PropertyViewModel> property = this._propertyService.PropertyList(PropertyStatusId);

            var selectList = new SelectList(property, propertyId, Address, ItemId);
            ViewBag.Properties = selectList;
        }

        public void PropertyDropDownListForLease(string propertyId, string FullAddress, int ItemId)
        {
            List<PropertyViewModel> property = this._propertyService.PropertyListForLease();

            var selectList = new SelectList(property, propertyId, FullAddress, ItemId);
            ViewBag.PropertiesForLease = selectList;
        }

        // public async Task<IActionResult> Index()
        public IActionResult LeaseList(int TenantId)
        {
            return Content("Hi LeaseList Page");
        }
        public IActionResult DependentList(int TenantId)
        {
            return Content("Hi DependentList Page");
        }
        public IActionResult VehicleList(int TenantId)
        {
            return Content("Hi VehicleList Page");
        }
    }
}

PropertyManagement.Web/Views/Shared/Partials/_LayoutFooter.cshtml
<!-- Layout footer -->
<nav class="layout-footer footer bg-footer-theme">
    <div class="container-fluid container-p-x pb-3">
        <a href="#" class="footer-link pt-3">Link 1</a>
        <a href="#" class="footer-link pt-3 ml-4">Link 2</a>
    </div>
</nav>
<!-- / Layout footer -->

PropertyManagement.Web/Views/Shared/Partials/_LayoutNavbar.cshtml
@{bool hideToggle = ViewData["LayoutNavbarHideToggle"] != null && ViewData["LayoutNavbarHideToggle"].ToString() == "True";}

<!-- Layout navbar -->
<nav class="layout-navbar navbar navbar-expand-lg align-items-lg-center bg-navbar-theme container-p-x" id="layout-navbar">
    <!-- Brand -->
    <a asp-page="/Index" class="navbar-brand">Asp.Net Core Starter</a>

    @if (!hideToggle)
    {
        <!-- Sidenav toggle -->
        <div class="layout-sidenav-toggle navbar-nav align-items-lg-center mr-auto mr-lg-4">
            <a class="nav-item nav-link px-0 ml-2" href="javascript:void(0)">
                <i class="ion ion-md-menu text-large align-middle"></i>
            </a>
        </div>
    }

    <!-- Navbar toggle -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#layout-navbar-collapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="layout-navbar-collapse">
        <div class="navbar-nav align-items-lg-center">
            <div class="nav-item"><a class="nav-link" href="#">Link 1</a></div>
            <div class="nav-item"><a class="nav-link" href="#">Link 2</a></div>
        </div>
    </div>
</nav>
<!-- / Layout navbar -->

PropertyManagement.Web/Views/Shared/Partials/_LayoutSidenav.cshtml
@{bool isHorizontal = ViewData["LayoutSidenavHorizontal"] != null && ViewData["LayoutSidenavHorizontal"].ToString() == "True";}
@{string currentPage = ViewContext.RouteData.Values["Controller"].ToString() + "/" + ViewContext.RouteData.Values["Action"].ToString();}
<!-- Layout sidenav -->
<div id="layout-sidenav" class="@(isHorizontal ? "layout-sidenav-horizontal sidenav-horizontal container-p-x flex-grow-0" : "layout-sidenav sidenav-vertical") sidenav bg-sidenav-theme">
    <!-- Inner -->
    <ul class="sidenav-inner@(!isHorizontal ? " py-1" : "")">
        <li class="sidenav-item@(currentPage == "Home/Index" ? " active" : "")">
            <a href="@Url.Action("Index", "Home")" class="sidenav-link"><i class="sidenav-icon ion ion-ios-contact"></i><div>Home</div></a>
        </li>
        <li class="sidenav-item@(currentPage == "Lease/Index" ? " active" : "")">
            <a href="@Url.Action("Index", "Lease")" class="sidenav-link"><i class="sidenav-icon ion ion-md-desktop"></i><div>Leases</div></a>
        </li>
        <li class="sidenav-item@(currentPage == "Tenant/Index" ? " active" : "")">
            <a href="@Url.Action("Index", "Tenant")" class="sidenav-link"><i class="sidenav-icon ion ion-md-desktop"></i><div>Tenants</div></a>
        </li>
        <li class="sidenav-item@(currentPage == "Property/Index" ? " active" : "")">
            <a href="@Url.Action("Index", "Property")" class="sidenav-link"><i class="sidenav-icon ion ion-md-desktop"></i><div>Properties</div></a>
        </li>
        <li class="sidenav-item@(currentPage == "Status/Index" ? " active" : "")">
            <a href="@Url.Action("Index", "Status")" class="sidenav-link"><i class="sidenav-icon ion ion-md-desktop"></i><div>Status</div></a>
        </li>
    </ul>
</div>
<!-- / Layout sidenav -->

PropertyManagement.Web/Views/Shared/Partials/_LeaseMonths.cshtml
    <div class="card-body demo-vertical-spacing">
        <div class="row">
            <div class="col-sm-4 mb-3">
                Year: <select class="selectpicker" data-style="btn-primary">
                    <option>2018</option>
                    <option>2017</option>
                    <option>2016</option>
                </select>
            </div>
            <div class="col-lg-12">
                <div class="demo-inline-spacing mt-3">
                    <button type="button" id="1" class="btn btn-secondary">Jan-Rent</button>
                    <button type="button" id="2" class="btn btn-secondary">Feb-Rent</button>
                    <button type="button" id="3" class="btn btn-secondary">Mar-Rent</button>
                    <button type="button" id="4" class="btn btn-secondary">Apl-Rent</button>
                    <button type="button" id="5" class="btn btn-secondary">May-Rent</button>
                    <button type="button" id="6" class="btn btn-secondary">Jun-Rent</button>
                    <button type="button" id="7" class="btn btn-primary">Jul-Rent</button>
                    <button type="button" id="8" class="btn btn-secondary">Aug-Rent</button>
                    <button type="button" id="9" class="btn btn-secondary">Sep-Rent</button>
                    <button type="button" id="10" class="btn btn-secondary">Oct-Rent</button>
                    <button type="button" id="11" class="btn btn-secondary">Nov-Rent</button>
                    <button type="button" id="12" class="btn btn-secondary">Dec-Rent</button>
                </div>
            </div>
        </div>
    </div>

PropertyManagement.Web/Views/Shared/Partials/_PropertyDetails.cshtml
<div class="card mb-12">
    <div class="row no-gutters">

            <div class="demo-inline-spacing mt-3">
                <a href="/Property/Edit?PropertyId=@ViewBag.PropertyId" class="btn btn-primary">Edit Property</a>
                <a href="/Property/RepairList?PropertyId=@ViewBag.PropertyId"class="btn btn-primary">Repairs</a>


        </div>
    </div>
</div>